# Generated by Django 4.1.4 on 2023-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Price', models.BigIntegerField(max_length=20)),
                ('discription', models.TextField()),
                ('productimage', models.FileField(upload_to='Myfiles')),
            ],
        ),
    ]
