# Generated by Django 4.1.4 on 2023-02-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertapp', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
